apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceType: git
  git:
    repo: https://github.com/Roopa-Sri3/configdemo
    branch: main
    dir: "/cluster/namespaces"
    auth: token
    secretRef:
      name: git-creds
